name: deepsegmentor
channels:
- peterjc123
- menpo
- conda-forge
- defaults
dependencies:
- python=3.8.1
- torch
- scipy
- opencv4
- scikit-image
- scikit-learn
- pip:
  - dominate==2.8.0
  - Pillow==9.5.0
  - numpy==1.24.3
  - torchvision==0.15.2
  - torchaudio==2.0.2
  - visdom==0.2.4
  - matplotlib==3.7.1
